example.property: "I AM IN THE DEFAULT"
spring.datasource.url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username: root
spring.datasource.password: wxz960324
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.initial-size: 6
spring.datasource.druid.min-idle: 5
spring.datasource.druid.max-active: 20
spring.datasource.druid.max-wait: 60000
spring.datasource.druid.time-between-eviction-runs-millis: 60000
spring.datasource.druid.min-evictable-idle-time-millis: 300000
spring.datasource.druid.validation-query: SELECT 1 FROM DUAL
spring.datasource.druid.test-while-idle: true
spring.datasource.druid.pool-prepared-statements: true
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
#spring.jpa.database: "POSTGRESQL"
#spring.datasource.platform:  "postgres"
#spring.jpa.show-sql: "true"
#spring.database.driverClassName: "org.postgresql.Driver"
#spring.datasource.url: "jdbc:postgresql://database:5432/eagle_eye_local"
#spring.datasource.username: "postgres"
#spring.datasource.password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
#spring.datasource.testWhileIdle: "true"
#spring.datasource.validationQuery: "SELECT 1"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"



